### ISSUE TITLE
Team.data returns empty JSON

### ISSUE THREAD

**Issue by crimsonpython24** [adl212/NT.py#1]
Ran

```python
import nitrotype

from huey import crontab
from huey.contrib.djhuey import periodic_task, task


@periodic_task(crontab(minute='*/1'))
def every_five_mins():
    team = nitrotype.Team('NTA')
    print(team.data)
```

but the console outputs `{}`

I am running in a Python virtual environment on a Windows machine. I cloned the repository into `venv\Lib\site-packages` and ran `python setup.py install`. I activated the virtual environment while running the script.

___

However, when I used 
```python
@periodic_task(crontab(minute='*/1'))
def every_five_mins():
    team = nitrotype.Team('NTA')
    print(team.leaders)
```
the console throws out
```
Traceback (most recent call last):
  File "C:\Users\xxx\venv\lib\site-packages\huey\api.py", line 367, in _execute
    task_value = task.execute()
  File "C:\Users\xxx\venv\lib\site-packages\huey\api.py", line 740, in execute
    return func(*args, **kwargs)
  File "C:\Users\xxx\tasks.py", line 10, in every_five_mins
    print(team.leaders)
AttributeError: 'Team' object has no attribute 'leaders'
```

Have I done the installation incorrectly, or is this caused by another problem?

______
As a matter of fact, after I cloned this repo and ran `pip install NT.py`, I get
```
Requirement already satisfied: NT.py in c:\xxx\venv\lib\site-packages\nt.py-3.5.5-py3.9.egg (3.5.5)
```

What could've gone wrong?

**Comment by crimsonpython24** [comment]
Nevermind, I did a few more tests and everything seems fine... although I'm unsure if using task schedulers will get my IP banned. 

Still couldn't figure out why sometimes the `.data` call returns empty brackets. Sorry for the incovenience.

**Comment by adl212** [comment]
I believe that was the wrong version

**Comment by crimsonpython24** [comment]
Can you please elaborate on that though @adl212

**Comment by adl212** [comment]
Hi, you were using version 3.5.5 which didn't completely work while 3.6.5 worked.
